version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - echo Installing Mocha...
      - yarn global add @nestjs/cli
  pre_build:
    commands:
      - echo Installing source YARN dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - yarn run build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
    - dist/**/*co
